# Generated by Django 5.1.2 on 2024-11-01 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='link',
        ),
    ]
